spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axon-kafka-example
    username: axon
    password: axon
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

axon:
  serializer:
    general: xstream
  eventhandling:
    processors:
      "[MyProcessor]":
        source: kafkaMessageSource
        mode: TRACKING
        threadCount: 1
        batchSize: 1
  kafka:
    clientid: myconsumer
    defaulttopic: mydefaulttopic
    consumer:
      group-id: boot
      bootstrapservers:
        - localhost:9092
        - localhost:9093
        - localhost:9094

logging:
  level:
    ROOT: INFO